source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'rack-cors'
gem 'puma'
gem 'sqlite3', '~> 1.6'
gem 'activerecord', '~> 7.0'
gem 'sinatra-activerecord'
gem 'rmagick' # Reusing from img-lib
gem 'json'
gem 'fileutils'
gem 'csv' # Required for Ruby 3.4.0+

group :development do
  gem 'rerun'
end

gem "rake", "~> 13.3"

gem "rackup", "~> 2.3"
